site_name: Store-Up Documentation
site_description: API and Architecture Documentation for Store-Up
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Domains:
    - Accounts: domains/accounts.md
    - Auth: domains/auth.md
    - Catalog: domains/catalog.md
    - RBAC: domains/rbac.md
    - Sale: domains/sale.md
    - Stock: domains/stock.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
