"""Add sale domain

Revision ID: 396449be7389
Revises: aa58134c5ed2
Create Date: 2026-08-24 19:53:21.673901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396449be7389'
down_revision = 'aa58134c5ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('seller_account_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed', 'returned')", name='chk_sale_status'),
    sa.CheckConstraint('discount >= 0', name='chk_sale_discount_positive'),
    sa.CheckConstraint('subtotal >= 0', name='chk_sale_subtotal_positive'),
    sa.CheckConstraint('total >= 0', name='chk_sale_total_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_seller_account_id'), ['seller_account_id'], unique=False)

    op.create_table('refunds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('processed_by', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processed', 'failed')", name='chk_refund_status'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refunds_sale_id'), ['sale_id'], unique=False)

    op.create_table('sale_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('refunded_quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('discount >= 0', name='chk_saleline_discount_positive'),
    sa.CheckConstraint('quantity > 0', name='chk_saleline_qty_positive'),
    sa.CheckConstraint('refunded_quantity <= quantity', name='chk_saleline_refunded_max'),
    sa.CheckConstraint('refunded_quantity >= 0', name='chk_saleline_refunded_positive'),
    sa.CheckConstraint('subtotal >= 0', name='chk_saleline_subtotal_positive'),
    sa.CheckConstraint('unit_price >= 0', name='chk_saleline_price_positive'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_lines_sale_id'), ['sale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_lines_variant_id'), ['variant_id'], unique=False)

    op.create_table('refund_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('refund_id', sa.Uuid(), nullable=False),
    sa.Column('sale_line_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='chk_refundline_qty_positive'),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], ),
    sa.ForeignKeyConstraint(['sale_line_id'], ['sale_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refund_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refund_lines_refund_id'), ['refund_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refund_lines_sale_line_id'), ['sale_line_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refund_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refund_lines_sale_line_id'))
        batch_op.drop_index(batch_op.f('ix_refund_lines_refund_id'))

    op.drop_table('refund_lines')
    with op.batch_alter_table('sale_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_lines_variant_id'))
        batch_op.drop_index(batch_op.f('ix_sale_lines_sale_id'))

    op.drop_table('sale_lines')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_sale_id'))

    op.drop_table('refunds')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_seller_account_id'))
        batch_op.drop_index(batch_op.f('ix_sales_number'))

    op.drop_table('sales')
    # ### end Alembic commands ###
